#!/usr/bin/env bash
#ddev-generated
## Description: Scaffold a new OXID module in htdocs/source/modules
## Usage: oxid-module-create <vendor> <module-id>
## Example: ddev oxid-module-create acme mymodule
set -e
vendor="$1"; id="$2"
[ -n "$vendor" ] && [ -n "$id" ] || { echo "Usage: ddev oxid-module-create <vendor> <module-id>"; exit 1; }
dir="/var/www/html/htdocs/source/modules/${vendor}/${id}"
[ -e "$dir" ] && { echo "$dir already exists."; exit 1; }
ns="$(echo "${vendor}" | sed -E 's/(^|[-_])(.)/\U\2/g')\\$(echo "${id}" | sed -E 's/(^|[-_])(.)/\U\2/g')"
mkdir -p "$dir/src"
cat > "$dir/metadata.php" <<PHP
<?php
\$sMetadataVersion = '2.1';
\$aModule = [
    'id'          => '${id}',
    'title'       => '${id}',
    'description' => '',
    'version'     => '0.1.0',
    'author'      => '${vendor}',
    'extend'      => [],
];
PHP
cat > "$dir/composer.json" <<JSON
{
    "name": "${vendor}/${id}",
    "type": "oxideshop-module",
    "autoload": { "psr-4": { "$(echo "${ns}" | sed 's/\\/\\\\/g')\\\\": "src/" } },
    "extra": { "oxideshop": { "target-directory": "${vendor}/${id}" } }
}
JSON
echo "Module created: $dir"
