#!/usr/bin/env bash
#ddev-generated
## Description: Clear the OXID cache (source/tmp)
## Usage: oxid-cc
source /var/www/html/.ddev/oxid/lib.sh
[ -d "$OXID_ROOT/source/tmp" ] || { echo "Directory $OXID_ROOT/source/tmp not found."; exit 1; }
oxid_clear_tmp
echo "OXID cache cleared."
