#!/usr/bin/env bash
#ddev-generated
## Description: Follow the OXID exception log
## Usage: oxid-log [tail-args]
## Example: ddev oxid-log -n 100
log="/var/www/html/htdocs/source/log/oxideshop.log"
if [ ! -f "$log" ]; then
  echo "No log yet, waiting for $log ..."
  while [ ! -f "$log" ]; do
    sleep 1
  done
fi
if [ $# -eq 0 ]; then set -- -n 50 -F; fi

oxid_unescape_log() {
  perl -pe 's/\\n/\n/g; s/\\r/\r/g; s/\\t/\t/g; s/\\"/"/g'
}

oxid_format_log() {
  if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
    oxid_unescape_log | sed -E \
      -e 's/^((\[[^]]+\]))/\033[36m\1\033[0m/' \
      -e 's/(Logger\.(ERROR|WARNING|NOTICE|INFO|DEBUG))/\033[1;31m\1\033[0m/g' \
      -e 's/(EXCEPTION_[A-Z_]+)/\033[1;31m\1\033[0m/g' \
      -e 's/(#[0-9]+)/\033[2;36m\1\033[0m/g'
  else
    oxid_unescape_log
  fi
}

tail "$@" "$log" | oxid_format_log
